/**
 * Generate src/generated/buildInfo.ts from the contract's ARC-56 artifact: the compiler that
 * produced the bundled bytecode. The generated client drops `compilerInfo`, and
 * verifyDeployment's `rebuild` check needs it to tell a toolchain mismatch from a source
 * mismatch.
 *
 * Usage: tsx scripts/generate-build-info.ts <sdk-root-path>
 */
import { readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'

const sdkRoot = process.argv[2]
if (!sdkRoot) {
  console.error('Usage: tsx generate-build-info.ts <sdk-root-path>')
  process.exit(1)
}

const spec = JSON.parse(
  readFileSync(resolve(sdkRoot, '../dnssec-oracle/smart_contracts/artifacts/dnssec_oracle/DnssecOracle.arc56.json'), 'utf-8'),
) as { compilerInfo?: { compiler: string; compilerVersion: { major: number; minor: number; patch: number } } }
if (!spec.compilerInfo) {
  console.error('DnssecOracle.arc56.json has no compilerInfo')
  process.exit(1)
}

const output = `// Generated by scripts/generate-build-info.ts from DnssecOracle.arc56.json. Do not edit.

/** The compiler that produced APP_SPEC.byteCode. */
export const COMPILER_INFO = ${JSON.stringify(spec.compilerInfo, null, 2)} as const
`
writeFileSync(resolve(sdkRoot, 'src/generated/buildInfo.ts'), output)
console.log(`Generated buildInfo.ts: ${spec.compilerInfo.compiler} ${Object.values(spec.compilerInfo.compilerVersion).join('.')}`)
