/**
 * Generate src/generated/errors.ts from every errors layer that can surface at runtime:
 * the oracle's own errors.algo.ts (message in a trailing comment) and the puya-ts-utils
 * MbrManager and RSA codes (message in a JSDoc comment above the constant).
 *
 * Usage: tsx scripts/generate-errors.ts <sdk-root-path>
 */
import { readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'

const sdkRoot = process.argv[2]
if (!sdkRoot) {
  console.error('Usage: tsx generate-errors.ts <sdk-root-path>')
  process.exit(1)
}

// `export const errX = 'CODE' // Message`
const trailing = /export const \w+ = '([A-Z0-9_]+)'\s*\/\/\s*(.+)$/gm
// `/** Message */ export const errX = 'CODE'`, or 'ERR:CODE' for plain asserts (rsaErrors)
const jsdoc = /\/\*\*\s*((?:(?!\*\/).)+?)\s*\*\/\s*export const \w+ = '(?:ERR:)?([A-Z0-9_]+)'/gs

const sources: { path: string; regex: RegExp; code: 1 | 2 }[] = [
  { path: '../dnssec-oracle/smart_contracts/dnssec_oracle/errors.algo.ts', regex: trailing, code: 1 },
  { path: '../dnssec-oracle/node_modules/@d13co/puya-ts-utils/src/mbrManager.algo.ts', regex: jsdoc, code: 2 },
  { path: '../dnssec-oracle/node_modules/@d13co/puya-ts-utils/src/rsaErrors.algo.ts', regex: jsdoc, code: 2 },
]

const errors: Record<string, string> = {}
const duplicates: string[] = []
for (const { path, regex, code: codeGroup } of sources) {
  const content = readFileSync(resolve(sdkRoot, path), 'utf-8')
  const before = Object.keys(errors).length
  for (const match of content.matchAll(regex)) {
    const code = `ERR:${match[codeGroup]}`
    const message = match[codeGroup === 1 ? 2 : 1].replace(/\s*\n\s*\*\s*/g, ' ').trim()
    if (code in errors) duplicates.push(`${code} in ${path}`)
    else errors[code] = message
  }
  if (Object.keys(errors).length === before) {
    console.error(`No error codes found in ${path}`)
    process.exit(1)
  }
}

if (duplicates.length > 0) {
  console.error(`Duplicate error codes, which must be unique across layers:\n  ${duplicates.join('\n  ')}`)
  process.exit(1)
}

const output = `// Auto-generated by scripts/generate-errors.ts - do not edit manually

/** Error codes (as logged on-chain, \`ERR:CODE\`) to human-readable messages. */
export const ErrorMessages: Record<string, string> = ${JSON.stringify(errors, null, 2)};
`
writeFileSync(resolve(sdkRoot, 'src/generated/errors.ts'), output)
console.log(`Generated ${Object.keys(errors).length} error messages`)
